on:
  push:
    paths:
      - "**.go"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - "dev/**"
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  go-testing:
    name: Main test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24'
      - name: Go setup
        run: go mod download
      - name: Go test
        run: go test ./... -count=1
  artifact-release:
    if: github.ref_type == 'tag'
    permissions: write-all
    needs: go-testing
    name: Artifact release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24'
      - name: Go dependencies
        run: go mod download
      - name: Build artifacts (Linux, Windows, MacOS)
        run: ./build-release.sh
      - name: Upload artifact
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build/*.tar
            build/*.zip