on:
  push:
    paths:
      - "**.go"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - "dev/**"
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  go-testing:
    name: Main test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24'
      - name: Go setup
        run: go mod download
      - name: Go test
        run: go test ./... -count=1
  artifact-release:
    if: github.ref_type == tag
    needs: go-testing
    name: Artifact release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: '>=1.24'
      - name: Go dependencies
        run: go mod download
      - name: Artifact build (Linux)
        run: go build -o build/linux/gorcon
      - name: Artifact build (Windows)
        run: GOOS=windows GOARCH=amd64 -o build/windows/gorcon.exe
      - name: Artifact build (MacOS)
        run: GOOS=darwin GOARCH=arm64 -o build/darwin/gorcon
      - name: Build artifacts
        run: ./build.sh
      - name: Upload artifact
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.tar
            build/*.zip